# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'S04-CameraFilters' do
   use_frameworks!

	pod 'RxSwift',    '~> 4.0'
	pod 'RxCocoa',    '~> 4.0'

 
  target 'S04-CameraFiltersTests' do
    inherit! :search_paths

  end

end
