# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'S12-NewsAppMVVM' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for S12-NewsAppMVVM
	pod 'RxSwift',    '~> 4.0'
	pod 'RxCocoa',    '~> 4.0'
  target 'S12-NewsAppMVVMTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
